name: Practice

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello There"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: second step
        run: print("Hello there")
        shell: python
