name: Step types

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello There"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello There from python")
        shell: python
  job-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "World, from acitons"
