name: Artifacts

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Some text in the artifact file" >> "artifact.txt"
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
      - run: cat artifact.txt
